/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.PacienteDAO;
import javax.swing.JOptionPane;
import modelo.Paciente;

public class CadPaciente extends javax.swing.JFrame {
    
    private Paciente objPacinte;
    private PacienteDAO objDAO;
    /**
     * Creates new form CadPaciente
     */
    public CadPaciente() {
        initComponents();
        /*
        //Centralizando a janela
        this.setLocationRelativeTo(null);
        // Impede que a janela seja redimencionada 
        this.setResizable(false);
        // Trocando cursor para HAND CURSOR(Maozinha)
        // jButtonRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        // Variavel con recebendo a conexao
        //carregarTable(null);
    }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id_paciente = new javax.swing.JTextField();
        nome_paciente = new javax.swing.JTextField();
        rg_paciente = new javax.swing.JTextField();
        end_paciente = new javax.swing.JTextField();
        gen_paciente = new javax.swing.JTextField();
        btn_Salvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tel_paciente = new javax.swing.JFormattedTextField();
        cpf_paciente = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("CADASTRO DE PACIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 11, -1, -1));

        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 59, -1, -1));

        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 85, -1, -1));

        jLabel4.setText("Telefone:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 114, -1, -1));

        jLabel5.setText("CPF:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setText("RG:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 166, -1, -1));

        jLabel7.setText("Endereço:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 192, -1, -1));

        jLabel8.setText("Gênero:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 218, -1, -1));

        id_paciente.setEditable(false);
        id_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pacienteActionPerformed(evt);
            }
        });
        jPanel1.add(id_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 56, 44, -1));

        nome_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_pacienteActionPerformed(evt);
            }
        });
        jPanel1.add(nome_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 82, 266, -1));

        rg_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rg_pacienteActionPerformed(evt);
            }
        });
        jPanel1.add(rg_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 163, 266, -1));

        end_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end_pacienteActionPerformed(evt);
            }
        });
        jPanel1.add(end_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 189, 266, -1));

        gen_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gen_pacienteActionPerformed(evt);
            }
        });
        jPanel1.add(gen_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 215, 266, -1));

        btn_Salvar.setText("SALVAR");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jButton1.setText("LIMPAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        try {
            tel_paciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(tel_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 200, -1));

        try {
            cpf_paciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_pacienteActionPerformed(evt);
            }
        });
        jPanel1.add(cpf_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_pacienteActionPerformed

    private void nome_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_pacienteActionPerformed

    private void rg_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rg_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rg_pacienteActionPerformed

    private void end_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_end_pacienteActionPerformed

    private void gen_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gen_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gen_pacienteActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        Paciente objPaciente = new Paciente();
        //objPaciente.setId(id_paciente.getText());
        objPaciente.setNome(nome_paciente.getText());
        objPaciente.setTelefone(tel_paciente.getText());
        objPaciente.setCpf(cpf_paciente.getText());
        objPaciente.setRg(rg_paciente.getText());
        objPaciente.setEndereco(end_paciente.getText());
        objPaciente.setGenero(gen_paciente.getText());
        
        //Validacação de dados
        
        if((nome_paciente.getText().isEmpty()) || (tel_paciente.getText().isEmpty()) || (cpf_paciente.getText().isEmpty()) || (cpf_paciente.getText().isEmpty()) || (rg_paciente.getText().isEmpty()) || (end_paciente.getText().isEmpty()) || (gen_paciente.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "Informe valores para os campos");
        }else{
            PacienteDAO dao = new PacienteDAO();
            dao.salva(objPaciente);
            JOptionPane.showMessageDialog(null, "Paciente " + nome_paciente.getText() + " inserido com sucesso! ");
        }
        setClear();
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setClear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cpf_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_pacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JFormattedTextField cpf_paciente;
    private javax.swing.JTextField end_paciente;
    private javax.swing.JTextField gen_paciente;
    private javax.swing.JTextField id_paciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome_paciente;
    private javax.swing.JTextField rg_paciente;
    private javax.swing.JFormattedTextField tel_paciente;
    // End of variables declaration//GEN-END:variables

    public void setClear() {
        id_paciente.setText(null);
        nome_paciente.setText(null);
        tel_paciente.setText(null);
        cpf_paciente.setText(null);
        rg_paciente.setText(null);
        end_paciente.setText(null);
        gen_paciente.setText(null);
    }
}
